Feature/navigation/premios/profile
vicenlu/ita-game pull request #78
Opened 2023-02-10 17:26 UTC by KhatJaba

links de puntos en home a histórico y premios a perfil

2023-02-11 11:04 UTC, Lahali reviewed
Tiene buena pinta!!

2023-02-11 11:05 UTC, Lahali approved these changes

2023-02-13 12:05 UTC, adaldin requested changes
Conflicto con la rama principal main por resolver

2023-02-14 12:38 UTC, Bazza6 approved these changes

2023-02-14 12:39 UTC, Bazza6 approved these changes

2023-02-14 13:37 UTC, vicenlu approved these changes

2023-02-14 13:42 UTC, vicenlu approved these changes

2023-02-14 13:42 UTC, merged